
# Conexión a PostgreSQL 
spring.datasource.url=jdbc:postgresql://ep-tiny-darkness-aqz1t3n8-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dt6P7jzpTwUm@ep-tiny-darkness-aqz1t3n8-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081



